name: Deploy [Staging]

on:
  push:
    branches:
      - develop

  workflow_dispatch:

jobs:
  deploy:
    name: Deploy project
    runs-on: ubuntu-latest
    environment:
      name: staging
      url: https://psi-staging.leticiabritto.com
    steps:
      - name: Deploy to Dokploy
        run: |
          OUTPUT=$(curl --silent --show-error --fail --request GET '${{secrets.DOKPLOY_WEBHOOK}}')
          if [ -z "$OUTPUT" ]; then
            echo "Erro: O webhook não retornou nenhuma resposta."
            exit 1
          fi
          echo "Deploy acionado com sucesso: $OUTPUT"