name: Deploy [Staging]

on:
  push:
    branches:
      - develop

  workflow_dispatch:

jobs:
  deploy:
    name: Deploy project
    runs-on: ubuntu-latest
    environment:
      name: staging
      url: https://psi-staging.leticiabritto.com
    steps:
      - name: Deploy to Dokploy
        run: |
          curl --request GET '${{secrets.DOKPLOY_WEBHOOK}}'